#:kivy 2.0.0

<CircleButton>:
    size_hint: None, None
    canvas:
        Color:
            rgba: self.color
        RoundedRectangle:
            radius: dp(self.height/2),
            size: self.size
            pos: self.pos
    Label: 
        text: root.text
        pos: (root.width/2, root.width/2)
        font_size: dp(root.height / 4)
        size_hint: None, None
        color: (0, 170, 0, 1)