<Reveal>:
    id: reveal
    canvas.before:
        Color:
            rgb: (1,.6,1)
        Rectangle:
            pos: self.pos
            size: self.size

<RevealTop>:
    id: reveal
    canvas.before:
        Color:
            rgba: (.5,0,.5,1)
        Rectangle:
            pos: self.pos
            size: self.size

<RevealBottom>:
    id: reveal
    canvas.before:
        Color:
            rgba: (1,.6,.6,1)
        Rectangle:
            pos: self.pos
            size: self.size
