#:kivy 2.0.0
<BusScreen>:
    size: 800, 480
    canvas.before:
        Color:
            rgba: self.color if self.image is not None else (0,0,0,0)
        Rectangle:
            pos: self.pos
            size: self.size
            source: self.image
    canvas:
        Color:
            rgba: self.slime
        Rectangle:
            pos: self.width - self.width / 2, 0
            size: self.width / 3, self.height
            